### ISSUE TITLE
Spinner randomly disappearing

### ISSUE THREAD

**Issue by JMTK** [heartcode/CanvasLoader#10]
So I use your spinner in an application I'm writing, and sometimes the spinner would disappear randomly, and wouldn't show up for a while then come back, with no user interaction or anything.

Our fix was overriding the show/hide functions, like so:

```
    this.cl = cl;
},

show: function() {
    this.cl.show();
    this.inherited(arguments);
},

hide: function() {
    this.cl.hide();
    this.inherited(arguments);
}
```

Not sure, I never called any hide function when it would disappear.

**Comment by heartcode** [comment]
HI Jake,

could you please tell me what browsers you had the problem with? If you could send me a link where I could try to reproduce the problem, that would be super helpful.

Thanks!

**Comment by JMTK** [comment]
I actually used this on an HP Touchpad for my app, Apollo: https://developer.palm.com/appredirect/?packageid=com.jmtk.apollo

The only browser testing we did was in Chromium, on Ubuntu. Can't say for sure if it disappeared on there, but on the Touchpad it would disappear after a while, then randomly come back. And as I said, just overriding the function fixed it.

**Comment by heartcode** [comment]
Hi @JMTK! I am not sure if it makes any sense now but do you still have the issue? I am not sure what exactly the `this.inherited()` method does in your code. I tried to check your application on the provided link, but it's no longer available.
