### ISSUE TITLE
utilize requestAnimationFrame?

### ISSUE THREAD

**Issue by blissdev** [heartcode/CanvasLoader#11]
Hi, This is more a question than a request, but I noticed some stuttering in the loader probably due to garbage collection and was wondering if requestAnimationFrame could be used on browsers that support it to smooth out rendering. It was even added to iOS 6. Perhaps that doesn't work with your FPS/Speed setup.

Thanks!

**Comment by heartcode** [comment]
Hi,

that is exactly the problem with `requestAnimationFrame` and hence it hasn't been implemented.

I've done some tests already about a year ago and it was simply too intense on the CPU and it simply wouldn't work as nicely. Unfortunately the only option is to stick to the `setInterval`.
