### ISSUE TITLE
Crashes (everything) when element with ID not found

### ISSUE THREAD

**Issue by joedyndale** [heartcode/CanvasLoader#16]
When the element in the HTML file with the ID specified in the CanvasLoader constructor isn't found, the script crashes completely, in many cases taking the whole application down with it. I suspect an exception is thrown, but is that really the best way to handle this situation?

**Comment by heartcode** [comment]
Thanks a lot for raising the issue, I will look into it ASAP.

**Comment by joedyndale** [comment]
Thanks. I've found a work-around for it in my app - but it would be nice to have this fixed eventually :)

Thanks for the great library by the way. CanvasLoader is excellent. Tried lots of animated GIFs at first, but they were all amazingly ugly. CanvasLoader is smooth :)

**Comment by brandfocus** [comment]
We're faced with the same problem. Have you been able to find the cause?
