### ISSUE TITLE
TypeError: Cannot call method 'appendChild' of null

### ISSUE THREAD

**Issue by djbacon** [heartcode/CanvasLoader#22]
I just added <script> tags to include canvasloader-min.js file and added generated code, but my javascript console gives me error "TypeError: Cannot call method 'appendChild' of null [http://127.0.0.1/scripts/heartcode-canvasloader-min.js?:1". Is this a bug or i'm missing something. I also have jquery .js included.

**Comment by heartcode** [comment]
Could you please provide a bit more details about how you got the error and where you think it came from?

**Comment by whitsey** [comment]
I also experienced this issue however, it was only when I placed the # before the id tag I was using.

i.e. instead of passing ('my-id') I was passing ('#my-id')
