### ISSUE TITLE
Minified version of the script is obsolete

### ISSUE THREAD

**Issue by artemgordinskiy** [heartcode/CanvasLoader#26]
Hi,
I've noticed that heartcode-canvasloader-min.js is more than a year older than the regular version. Just a heads up.

Thanks for the script, it's awesome!

**Comment by heartcode** [comment]
You're absolutely right @ArtemGordinsky! I am well aware of this library being quite out of date and I am planning to do some rewrite, optimisation and updates to the code as soon as I have some free time.

**Comment by artemgordinskiy** [comment]
Sorry, I guess I wasn't clear enough. The library itself is fine (at least it worked for me nicely). I was referring to the minified version of your library, namely – heartcode-canvasloader-min.js. I was saying that it's obsolete relatively to the original, unminified version.
